spring.application.name=service-register

spring.profiles.active=dev

# Nouvelle syntaxe OBLIGATOIRE depuis Spring Boot 3.x + Spring Cloud 2023
spring.config.import=configserver:http://localhost:8888
