spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=https://github.com/azizndoye68/config-data.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true

# Exposer le endpoint health pour le healthcheck Docker
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always